AllCops:
  NewCops: enable
require:
  - rubocop-rails
  - rubocop-rspec
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
Style/Documentation:
  Enabled: false
