default: &default
  additional_paths: []
  cache_manifest: false
  cache_path: tmp/cache/webpacker
  extensions:
  - .mjs
  - .js
  - .sass
  - .scss
  - .css
  - .module.sass
  - .module.scss
  - .module.css
  - .png
  - .svg
  - .gif
  - .jpeg
  - .jpg
  extract_css: false
  public_output_path: packs
  public_root_path: public
  source_entry_path: packs
  source_path: app/javascript
  static_assets_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .tiff
  - .ico
  - .svg
  - .eot
  - .otf
  - .ttf
  - .woff
  - .woff2
  webpack_compile_output: true
development:
  <<: *default
  compile: true
  dev_server:
    compress: true
    disable_host_check: true
    headers:
      'Access-Control-Allow-Origin': '*'
    hmr: false
    host: localhost
    https: false
    inline: true
    overlay: true
    port: 3035
    pretty: false
    public: localhost:3035
    quiet: false
    use_local_ip: false
    watch_options:
      ignored: '**/node_modules/**'
production:
  <<: *default
  cache_manifest: true
  compile: false
  extract_css: true
test:
  <<: *default
  compile: true
  public_output_path: packs-test
